parse-community/parse-dashboard

package.json
=> Update node-sass version (related to #47)

Parse-Dashboard/index.js, package.json, src/dashboard/Apps/AppsIndex.react.js, src/dashboard/Dashboard.js
This will load the available features from npm when the server is started and ship the new features down to the client.
=> Display features available in newest version

src/dashboard/Data/ApiConsole/generateCurl.js
=> Fixed cURL serverURL

src/components/Sidebar/AppsSelector.react.js, src/dashboard/Data/Browser/Browser.react.js, src/lib/ColumnPreferences.js
Save ordering between different use
=> Save ordering between different use

package.json, src/components/ACLEditor/ACLEditor.react.js, src/components/PermissionsDialog/PermissionsDialog.example.js, src/components/PermissionsDialog/PermissionsDialog.react.js, src/dashboard/Data/Browser/Browser.react.js, src/dashboard/Data/Browser/BrowserToolbar.react.js, src/dashboard/Data/Browser/DataBrowser.react.js, src/dashboard/Data/Browser/SecurityDialog.react.js, src/lib/ParseApp.js, src/lib/stores/SchemaStore.js
=> Clp editor

Parse-Dashboard/index.js
New features from latest package weren't being properly parsed. This caused "Upgrade" banner never to show.
=> Fixed bug with determining new features in latest version.

src/lib/AJAX.js
=> Improve AJAX matching for mount paths urls

src/components/Sidebar/SidebarHeader.react.js, webpack/base.config.js
=> Pulling of parse-dashboard version from package.json

src/components/Field/Field.scss, src/components/Modal/Modal.scss, src/components/PushPreview/PushPreview.scss, src/dashboard/Push/Push.scss
Hey guys,
I made a small CSS fixes just to start from somewhere :)
=> Small visual fixes

README.md
I added badges for travis-ci and npm.
=> added ci & npm badges

package.json, src/components/LogView/LogViewEntry.react.js, src/dashboard/DashboardView.react.js, src/dashboard/Data/Logs/Logs.react.js
This is fairly incomplete but probably valuable regardless - at least you can see the logs. We can upgrade level based filtering and so-on later.
=> Add basic support for logs viewing

Dockerfile
1. using npm run dashboard to generate bundles/dashboard.bundle.js
2. shrink docker image size
=> Tweak Dockerfile (Fixes #136)

src/dashboard/Data/Browser/Browser.react.js, src/dashboard/Data/Browser/Browser.scss, src/dashboard/Data/Browser/BrowserToolbar.react.js
This isn't quite ready but I'm soliciting input if you wouldn't mind taking a look.
=> Add refresh button to data browser

package.json
Also removes duplicate log viewer feature in array
=> Package.json 1.0.9

Parse-Dashboard/app.js, Parse-Dashboard/index.js, README.md, src/dashboard/Apps/AppsIndex.react.js, src/dashboard/Apps/AppsIndex.scss, src/lib/ParseApp.js
Thanks @drew-gross for pointing me the direction. 
See the Readme diff for more info.
This should close #269
=> Allows showing app icons (or placeholder)

src/dashboard/Data/Browser/DataBrowser.react.js
Adding the possibility to cancel the editing of a field in the data browser by pressing the ESC key.
=> Added cancellation of editing in data browser by pressing ESC key

src/components/GeoPointEditor/GeoPointEditor.react.js
Fixing code styling as suggested by @drew-gross in pull request #373.
Thanks so much for the constructive suggestions!
=> Geoeditor comma features code styling

src/lib/ParseApp.js
Update endpoint url for deleting all rows in dashboard
Maybe we can merge later, i.e. just before next release of parse server, in case there are changes again
=> Update endpoint url

Procfile
The profile now runs on Heroku without any changes needed.
=> Updated paths Procfile

src/components/Sidebar/FooterMenu.react.js, src/components/Sidebar/Sidebar.react.js
I saw that someone suggested to change the footer links to open in a new tab.
Hope this is the proper way.
=> Changed Sidebar Footer links to open in a new tab

src/dashboard/Data/Browser/Browser.react.js
Fixes #496 
Anonymous function parameter 'column' misspelling
=> fix misspelling

Parse-Dashboard/app.js
=> Revert "using mount path when mounted as express module"

CHANGELOG.md, Parse-Dashboard/Authentication.js, Parse-Dashboard/app.js, src/components/Sidebar/FooterMenu.react.js, src/lib/tests/e2e.js, src/login/Login.js
Fixes ParsePlatform/parse-dashboard#604
=> Use mountPath for all log in and log out redirects

.github/ISSUE_TEMPLATE.md
I changed to the latest versions of Parse Server and Parse Dashboard
=> Changes in versions

src/login/Login.js
It would be more convenient to set focus on the username field when user starts to login.
=> Autofocus on the username input field when user starts to login

src/components/Sidebar/FooterMenu.react.js, src/components/Sidebar/Sidebar.react.js, src/dashboard/Data/Browser/SecurityDialog.react.js
link on the bottom failed, so I updated all old links.  not sure how to publish.
also not https but i think it would be better to get this out there with http and then switch to https when/if cert is good since current doc link is busted.
=> update links to point to parse-community/parseplatform.org

src/dashboard/Data/Browser/BrowserTable.react.js
Added title to "Add Row" button at the bottom of the table to make the functionality more clear.
=> Added title to the Add Row Button

src/dashboard/Data/Browser/BrowserTable.react.js
fixes https://github.com/ParsePlatform/parse-dashboard/issues/668
=> fix table scrolling

src/dashboard/Data/Config/Config.react.js
=> Sort config data according to parameter names

src/stylesheets/globals.scss
Fixes `invalid keyframes name` by wrapping them for interpolation
=> Updates global.scss

src/dashboard/Push/PushDetails.react.js
=> Ensure we traverse the payloadJSON properly

src/components/Modal/Modal.scss
=> Fix modal icon position

src/dashboard/Push/PushNew.react.js
I believe is the most simple solution for this #891
=> Issue: Don't make Everyone the default audience on Push

Dockerfile
**Summary:**
This pull request updates the Dockerfile for the project to improve the build artifacts and deployment speed of the built container.  This is my first PR so if it needs formatting differently please let me know :)
**Related issues:** 
#830 and #640 
**Summary of changes:**
- Switched to alpine linux base image for smaller image sizes
- Created a multi-stage build allowing final image to only contain production dependencies
- All webpack compilation occurs during the docker build phase rather than some occurring when the container is executed.  This drastically reduces the time-to-live for the deployed dashboard
**Performance Impact**
Whilst initial container build time is increased, the container size and launch time are decreased.  The refactored Dockerfile should benefit …
=> Updated Dockerfile to use a multi-stage build.

src/components/ChromeDropdown/ChromeDropdown.react.js
Convert width from string to number, I don't know what caused this.
Before:
After:
=> Fix Filter Width

CHANGELOG.md, Parse-Dashboard/app.js, src/components/Sidebar/SidebarHeader.react.js
This is a fix for https://github.com/parse-community/parse-dashboard/issues/800
=> Show dashboard username when using user & pass to login

src/components/FileEditor/FileEditor.react.js
=> Fix upload json parse file

src/dashboard/Data/Browser/Browser.react.js, src/dashboard/Data/Browser/BrowserToolbar.react.js, src/dashboard/Data/Browser/CloneSelectedRowsDialog.react.js
Closes https://github.com/parse-community/parse-dashboard/issues/924
=> Support for clone object

package-lock.json, src/lib/AppsManager.js
If there is an error connecting to the server, don't run count operations
Updates package-lock.json with react-helmet
=> Unhandled Promise Rejection fix

.travis.yml
=> CI: do not use cached directory

package-lock.json
=> Fix: Master fails to install graphql-playground #1131

package-lock.json, package.json
Version 22.13.1 has a [bug](https://github.com/jest-community/eslint-plugin-jest/issues/339) and a fix was released on 22.13.2.
=> chore: Update eslint-plugin-jest to 22.13.2

package-lock.json, package.json, src/dashboard/index.js
[Source](https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#usebuiltins-entry-with-corejs-3)
=> fix: Update core-js@3

src/dashboard/Data/Browser/Editor.react.js
=> feat: String editor resizable

src/components/PushAudienceDialog/InstallationCondition.react.js
ref #581
Screenshots:
- Issue
- New behavior
- Dropdown closed
- Dropdown opened
=> fix: Boolean dropdown on installation condition

src/dashboard/Data/Browser/BrowserToolbar.react.js, src/dashboard/Data/Browser/DataBrowser.react.js
Close https://github.com/parse-community/parse-dashboard/issues/1271
=> Fix: filter tab not working for _User, and ohter classes starting with _

CHANGELOG.md, package-lock.json, package.json
=> Release v2.0.3

CHANGELOG.md, package-lock.json, package.json
Update Package Lock file to handle dependencies (corejs3).
CoreJS is no longer a dev dependency 👇
https://github.com/parse-community/parse-dashboard/compare/2.0.5?expand=1#diff-32607347f8126e6534ebc7ebaec4853dR917
=> ⚡️ Release v2.0.5

package-lock.json, package.json
Node: **14.4.0**
NPM: **6.14.4**
OS: **macOS 10.15.7**
Webpack build failure:
```
Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
```
Similar issue: https://github.com/JeffreyWay/laravel-mix/issues/2383
=> Fixed Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'

package-lock.json, package.json
Closes: https://github.com/parse-community/parse-dashboard/issues/1555
=> chore: Bump parse to 2.17.0

src/dashboard/Data/Jobs/Jobs.react.js
=> Add Finished At to Job Status

src/components/BrowserFilter/BrowserFilter.react.js, src/components/BrowserFilter/FilterRow.react.js, src/components/DateTimeEntry/DateTimeEntry.react.js, src/components/DateTimePicker/DateTimePicker.react.js, src/components/Popover/Popover.react.js, src/lib/hasAncestor.js
- applied changes of this [pr](https://github.com/parse-community/parse-dashboard/pull/1638)
- catching onClick event, to stop propagating to parent
=> Fix date filters

src/dashboard/Push/PushNew.react.js
Hiding setup locales message on adding all locales messages when locales message is set up.
=> Push Notification: Hiding setup locales message on adding all locales

src/components/FileInput/FileInput.react.js, src/components/FileInput/FileInput.scss, src/dashboard/Data/Browser/AddColumnDialog.react.js, src/dashboard/Data/Browser/Browser.react.js
When creating a column of type file and selecting a file as the default value, there isn't any kind of feedback for selected file & don't know if the file uploading failed.
- showing a error note, if uploading fails
- changing file input value
- showing a spinner while uploading file
=> update on file change

CHANGELOG.md, src/components/BrowserCell/BrowserCell.react.js, src/components/BrowserCell/BrowserCell.scss
This pr solves https://github.com/parse-community/parse-dashboard/issues/1775
Related issue: #`1775`
https://user-images.githubusercontent.com/44117648/131889626-e743e125-6b24-434b-84e1-0cffabd7eca6.mp4
=> Improve ui for array of pointer field

.github/workflows/ci.yml
Bump ci env
Related issue: #n/a
- bump Node.js 14.17.6 to 14.18.0
n/a
=> ci: bump environment
