parse-community/parse-dashboard

- Parse-Dashboard/index.js
- README.md
- package.json
- Adds support for --config, --port --allowInsecureHTTP
- Adds support for PARSE_DASHBOARD_ALLOW_INSECURE_HTTP
- Adds npm start script for easy deployments
- Adds documentation for running behind HTTPS load balancers
fixes #54
> Adds commander CLI, improve remote deployments

- package.json
> Require minimum node version

- components/Button/Button.react.js
* Declares a `hasOnClick` variable to make the ternary expression returning the `clickHandler` value shorter and more clear
* Creates a `noop` function outside the component function so that the component doesn't have to create a new function every time new props are passed.
> Make clickHandler registration more clear

- .gitignore
- Parse-Dashboard/index.js
- README.md
- bin/parse-dashboard
- gulpfile.js
- package.json
- Adds gulp build system to build the parse-dashboard dist
- Adds instruction for safe production deployments
- Adds ability to build npm package
- npm package only contains dist/ and optimized bundles
- 5 steps configuration for production deployments.
> Adds distribution with built package

- package.json
Source map debugging for client side errors like: #73.
Adding as separate a development dedicated script.
> Adding devtool eval to better debug client side errors.

- src/components/BrowserCell/BrowserCell.react.js
- src/dashboard/Data/Browser/BrowserTable.react.js
For pointers to users the constructor is Parse.User, not Parse.Object, so `instanceof` is necessary.
> Fix issues with arrays contiaining null or pointers to users. Fixes #105.

- src/parse-interface-guide/routes.js
Patch for PIG, per console warning
> Use browserHistory from React Router 2 instead of createHashHistory

- src/dashboard/Data/Browser/Browser.react.js
- src/dashboard/Data/Browser/BrowserToolbar.react.js
The data browser 'Edit' menu has related options like 'Add a Row' or 'Delete this class', so 'Add a class' is a natural addition.
> Add an 'Add a Class' entry to the edit menu

- src/dashboard/Data/Browser/Browser.react.js
The Parse Dashboard tracks a count of each Parse Class and displays it
in the data browser. When a user visits and app, then visits a different
app, then goes back to the first app, the counts don't display.
It turns out that the Parse.Promise polyfill is incorrect. While an
resolved Promise should always schedule a microtask, the Parse.Promise
polyfill makes it possible for a Promise to be executed immediately,
which seems to happen here when the network request is cached (jumping
back to a previously viewed application).
This fixes the bug by moving the promise execution after the setState
call that may clear `this.state.counts`. However, the more correct
solution would be to fix the polyfill in Parse-SDK-JS, or better yet,
use someone else's, like Forbes': …
> Fix missing class counts when switching apps

- src/dashboard/Dashboard.js
Specifically with case of parse-server missing masterkey in mind.
I'm hoping this will alleviate users that haven't configured their parse server with a masterKey. I'm sure we can try to update other things to make it clearer but one step fwd.
> Updating error message handling.

- package.json
- src/dashboard/index.js
Adds polyfills for old browsers:
dashboard.bundle.js  1.11 MB       0  [emitted]  dashboard
dashboard.bundle.js  1.19 MB       0  [emitted]  dashboard
dashboard.bundle.js  8.87 MB       0  [emitted]  dashboard
dashboard.bundle.js   9.6 MB       0  [emitted]  dashboard
The impact on production server is negligible 
fixes #166
> adds polyfills

- src/dashboard/Data/Browser/Browser.react.js
- src/dashboard/Data/Browser/BrowserToolbar.react.js
- src/lib/ParseApp.js
Before objects count is cached with app schema and only shows for 'raw' classes presentations. This change adds support for objects count for relation presentations. The count itself is fetched every time Browser component gets new relation.
> Add support for relation's count in toolbar details

- README.md
- src/dashboard/Apps/AppsIndex.react.js
- src/lib/ParseApp.js
Addresses https://github.com/ParsePlatform/parse-dashboard/issues/213
> Change app mode to production to show green badge

- Parse-Dashboard/index.js
- README.md
> allow to set a custom host

- CHANGELOG.md
- src/components/Dropdown/Dropdown.scss
This will hopefully prevent people from being confused about there being more items available in the dropdown if you scroll
> Dropdown height

- Parse-Dashboard/index.js
- README.md
Hello,
While we are at it, could we also add an option for the mount path ? This may be useful when running the dashboard behind an NGINX proxy, for instance.
These changes should enable one to set a mount path for the dashboard, e.g.
```
$ parse-dashboard --config myconfig.json --mountPath /dashboard
The dashboard is now available at http://0.0.0.0:4040/dashboard
```
As stated in #235, only mount paths that are not prefixes of `"parse-dashboard-config.json"` seem to work so far...
> allow to set a custom mount path

- src/components/Sidebar/AppsSelector.react.js
- src/components/Sidebar/Sidebar.scss
This also makes the sidebar open by default on narrow windows, as the original code causing the error was code that fixed a bug when the window was loaded while the sidebar was off-screen.
> Fix warning in AppSelector (Fixes #104)

- Parse-Dashboard/app.js
- README.md
Restrict access to selected apps based on user preferences defined in
the dashboard configuration file.
```
{
"apps": [ … ],
"users": [
{
"user":"user1",
"pass":"pass1",
"apps": [{"appId": ""}, {"appId": ""}]
}
]
}
```
> Separating app access based on user preferences

- README.md
Added additional headers and reorganized README so that it's easier to follow from a local installation / deployment scenario perspective.
Added a table of contents with "jump-to" links for easier navigation of the document.
Closes Issue #290.
> Update README.md with additional headers and TOC

- Parse-Dashboard/index.js
I've added SSL/HTTPS support to the Dashboard Express app via two new command line options. An example command for SSL is:
```bash
$ parse-dashboard --config ~/dash-config.json --sslKey /etc/letsencrypt/live/domain.com/privkey.pem --sslCert /etc/letsencrypt/live/domain.com/cert.pem
```
This will load app details from the config file and load current SSL keys as generated from letsencrypt.
Some basic info came from #204.
Let me know if I'm missing anything, or if you'd like me to add details to the README file as well.
> Added SSL Support to Dashboard

- README.md
Thanks to @flovilmart in pull request #209 we can now use Parse Dashboard as express middleware. The readme is now updated with instructions on how to do this.
> Update README.md with express middleware instructions

- Parse-Dashboard/index.js
`app.enable('trust proxy');` when you are running the dashboard behind an HTTPS load balancer or proxy.
> Allow trust proxy if allowInsecureHTTP

- src/components/AppBadge/AppBadge.scss
At some point a bug got introduced that had them on the left, touching the app name.
> Fix badge location

- Parse-Dashboard/app.js
- Parse-Dashboard/index.js
- Parse-Dashboard/parse-dashboard-config.json
> gives the developer feedback if something is wrong with the icons directory

- Parse-Dashboard/app.js
- README.md
> fixed error call

- src/lib/ParseApp.js
Right now the parse-dashboard is sending always the same 10 first info logs because no params are sent (it uses the default params from the parse-server).
Here the params are send in the querystring.
If someone has a better solution I'm interested :)
> Fix getLogs function

- CONTRIBUTING.md
This is almost painful, but it is an essential line in the documentation, so I had to do it.
> Fix spelling of dashboad to dashboard

- src/components/GeoPointEditor/GeoPointEditor.react.js
Added support for certain comma (,) related features to the GeoPointEditor.
Allows you to paste a coordinate "23.45, 10.00" into the latitude field and it will auto populate.
Allows you to paste an incomplete coordinate "23.45, " into the latitude field and it will auto advance to longitude. If you type in "23.45," it will also auto advance on the ,.
This is my first pull request, so if code quality is not up to par, or I did something wrong in this process please tell me.
> Add point spliting and auto focusing to the GeoPointEditor

- src/components/PushOpenRate/PushOpenRate.react.js
- src/dashboard/DashboardView.react.js
- src/dashboard/Push/PushConstants.js
- src/dashboard/Push/PushDetails.react.js
- src/dashboard/Push/PushIndex.react.js
- src/lib/ParseApp.js
- src/lib/PushUtils.js
Originally Parse Dashboard used some custom endpoints to Parse for fetching push notifications and statuses. Now, the "_PushStatus" class in Parse Server can be queried directly when using the master key. From what I can tell, this has been available since Parse Server v2.2.8.
There's still *a lot* of stale/unused code regarding push notifications (experiments, audiences, push opens, scheduled pushes, etc.). I'm not sure what (if any) of those features will eventually be implemented, so I kept most of that code untouched.
This pull request gives the basic functionality of:
1. Viewing the list of all pushes with the "load more" button for loading more.
2. The detailed view of individual pushes to show pushes sent and targeting.
One thing to note is that Parse Server has a "source" of …
> Update push activity and push details views to query _PushStatus

- src/dashboard/Push/PushIndex.react.js
When updatedAt is a date object and pushTime is null, this crashes. Workaround by checking `typeof time`, since we don't have local time push in Parse Server anyway.
> Fix past pushes page

- src/lib/ParseApp.js
Related to #124 
Merge only if ParsePlatform/parse-server#2032 accepted!
> Delete all rows in class

- src/lib/AppsManager.js
Always sorts before returning apps() - should probably live somewhere else but I'm unable to find a suitable location for it. Solves #415
> Sorting applications by name in the dashboard, #415

- src/dashboard/Push/PushDetails.react.js
- src/lib/PushUtils.js
- Correct schema for target table parser: fix channels not shown
- Fix empty value if value type is boolean
> Bug fixes: target table parser in Push Notification Details

- README.md
I added documentation in the readme for configuring Parse Dashboard using environment variables. I wasn't sure how to format so some guidance would be welcome!
I signed the CLA right before sending the PR, not sure why the bot didn't pick it up.
> Add configuration through environment variables

- Parse-Dashboard/app.js
The dashboard did not use the MOUNT_PATH env var when used as express module.
> using mount path when mounted as express module

- Parse-Dashboard/app.js
- README.md
- package.json
You can now add an encrypted password (bcrypt) to the config and login with it.
> Added the ability to accept encrypted passwords

- src/dashboard/Data/Browser/Browser.react.js
When attempting to sort by the `createdAt` column, we would still apply
the default sort ordering of `-createdAt`, meaning that we would specify
a sort order of `createdAt,-createdAt`. When Parse-Server gets a sort
order in which the same field appears more than once, it will use the
last entry for the field in its sorting. This means that the sort the
user has selected is overwritten by the default sort we apply.
We now check to see if the sort we are applying is already on the
`createdAt` field, and if so we do not apply the default ordering.
Fixes #447.
> Allow sorting by `createdAt` ascending

- Parse-Dashboard/Authentication.js
- Parse-Dashboard/app.js
- README.md
- src/lib/tests/Authentication.test.js
Discovered that my previous encrypted password implementation allowed the user to type the hash and be authenticated. I feel like that isn't going to be expected, so, I added an options config option to enable encrypted passwords.
> Made the encrypted passwords an option

- Parse-Dashboard/Authentication.js
- src/dashboard/Data/Browser/BrowserToolbar.react.js
I added a shortcut to add a row to the data browser in the toolbar header. It might seem redundant, but it's easier to get to than the one in the Edit menu, and the one at the bottom can be too far down on long lists.
> Added add row button to data browser toolbar.

- Parse-Dashboard/Authentication.js
Addresses @johnnydimas comments in #510 (which he already fixed in #512) and also documents the methods.
> Added support for node 4.3 and some documentation to Authentication.js

- package.json
- src/dashboard/Dashboard.js
- src/dashboard/DashboardView.react.js
- src/dashboard/Data/Jobs/Jobs.react.js
- src/lib/ParseApp.js
- src/lib/stores/JobsStore.js
- Removes the scheduled endpoint (we don't schedule on parse-server)
- Adds /all endpoint with just run method
- Supports _JobStatus query
> Adds support for viewing parse-server based jobs

- src/dashboard/Data/Browser/SecurityDialog.react.js
Two fixes for the "Learn more about CLPs and app security" link from Edit Class Level Permissions dialogue.
- Fix href to point to github instead of parse.com
- Fix the link not opening a new tab
> Fix CLP documentation link URL

- CONTRIBUTING.md
Switch Create with Update as the `parse-dashboard-config.json` 
file already exists in the `Parse-Dashboard` folder.
> Fix text in CONTRIBUTING.md

- src/components/Calendar/Calendar.react.js
Code in DateUtils uses local time (e.g. getMonth() instead of getUTCMonth() etc.) so for compatibility state.currentMonth is also now considered local time.
props.local is used in only 2 places:
1. When constructing state.currentMonth to decide if props.value is in local or UTC time
2. When sending an outgoing onChange event to convert currentMonth back to local or UTC time
There is no code path where props.local is true so this has not been tested. I can't think why this would be required so would like to remove in a non-bugfix PR.
Have tested in timezones UTC+1, UTC-12, UTC+14 (in which case local time was one day after UTC)
> Fix calendar month/current selection and clicking

- Parse-Dashboard/app.js
- Parse-Dashboard/index.js
- README.md
(Thanks to http://jaketrent.com/post/https-redirect-node-heroku/)
When hosting on Heroku, it turns out the request.secure will always be false, even if the client requests over HTTPS. Instead, Heroku adds an HTTP header 'x-forwarded-proto' specifying the protocol used ('http' or 'https'). For those on Heroku, this additional check will allow the HTTPs check to work. For those not on Heroku (where this header doesn't exist), it won't do anything.
A followup PR to https://github.com/ParsePlatform/parse-dashboard/pull/454.
> Added support for trusting proxies w/ HTTPS

- CHANGELOG.md
- src/components/PushAudienceDialog/InstallationCondition.react.js
> #561: Fixes issue with installation conditions that are pointers

- Parse-Dashboard/Authentication.js
- src/lib/tests/Authentication.test.js
When authenticating to dashboard using encrypted passwords, bcrypt throws an error in the authenticate function that userToTest.pass is undefined. This happens when the userToTest object does not contain a password, which happens every time deserializeUser is called. The solution is to check the usernameOnly flag when initializing passwordMatches to avoid passing an undefined value to bcrypt.
> Check usernameOnly parameter in passwordMatches

- CHANGELOG.md
- src/lib/stores/ConfigStore.js
I believe this will resolve #339.  When the masterKey is not being passed on the FETCH, then the server is returning a 401.
I had the same issue with version 1.0.19 of the dashboard and 2.2.24 of the server.
> Updated to pass masterKey for Config get request

- src/dashboard/Apps/AppsIndex.react.js
The apps list in `src/dashboard/Apps/AppsIndex.react.js` is sorted by `name` now (asc).
It was sorted by the `createdAt` attribute.
> AppsIndex: apps are sorted by name now.

- src/lib/stores/JobsStore.js
Without the master key present, fetching the jobs list from `/cloud_code/jobs` fails with 403 unauthorized.
> Fix fetching jobs list with master key

- CHANGELOG.md
- src/dashboard/Data/Browser/Browser.react.js
> Data browser updates object count when table is filtered

- src/dashboard/Data/Jobs/Jobs.react.js
- src/dashboard/Data/Jobs/JobsData.react.js
- src/dashboard/Data/Logs/Logs.react.js
Also, this PR fixes 2 React warnings related to not setting a key in a few components (See Logs.react.js and Jobs.react.js)
Fixes #295
> Don’t call unsupported endpoints in Parse Server

- src/components/Sidebar/FooterMenu.react.js
- src/components/Sidebar/Sidebar.react.js
- src/components/Sidebar/Sidebar.scss
* **Docs** point to the right link
* Removed the **Downloads** link, replacing it with the **GitHub** link
* Added more relevant links in the more section
**Before:**
**After:**
@hramos you might like this one :)
> Update and add links to sidebar footer

- src/components/FileInput/FileInput.react.js
- src/dashboard/Data/Config/Config.react.js
This PR fixes the display of `Parse.File`s  and GeoPoints in the Config section of the Dashboard.
Now that @flovilmart fixed saving Files to Config in Parse Server (ParsePlatform/parse-server#3457), this is the last bit to have it working in the dashboard.
@JeremyPlease @dvanwinkle @steven-supersolid if anyone of you could review, it would be great.
> Fix display of ParseFile in Config

- CHANGELOG.md
- package.json
Due to the latest fix on #666, I believe we should release a new version after it's merged.
> Version 1.0.25

- package.json
- src/dashboard/Dashboard.js
The specific issue this fixes for us is https://github.com/ParsePlatform/Parse-SDK-JS/issues/311.
I've only done smoke testing of this fix, but will be deploying it to our staging instance today and will update if I run into any issues.
> Update parse SDK to 1.9.1.

- Dockerfile
Specifying the image as argon-slim has two benefits:
- Reduce overall size of image
- Keep up to date with regards to node 4.x
We also want to set the npm log level from info to error so that it doesn't spew output while building.
> Use slim docker image + only print >warning on npm i

- src/components/BrowserCell/BrowserCell.react.js
- src/components/FileEditor/FileEditor.react.js
- src/components/FileEditor/FileEditor.scss
Instead of clicking in the file cell to download, and double clicking in the white part of the cell to edit/delete, this change adds download into the editor, so it’s easier to edit if needed, while keeping the download functionality.
This addresses the problems raised in #713
> Moves download option into file editor

- src/dashboard/Data/Browser/Browser.react.js
- src/dashboard/Data/Browser/Browser.scss
- src/dashboard/Data/Browser/Notification.react.js
This PR enables the functionality we had in the original Parse.com dashboard (before the redesigned one) and closes #715 
When a save/delete succeeds or fails, it will display a small notification for 3 users. I didn't write any new functionality, I only fixed/extended the `Notification` component.
It doesn't handle additions to and removal of relationships, but it does handle:
* Saving new object
* Updating existing object
* Deleting object
* Failure when saving object
* Failure when [deleting one or multiple objects](http://parseplatform.org/Parse-SDK-JS/api/classes/Parse.Object.html#methods_destroyAll)
> Shows notifications upon success or failure of save and delete objects

- CHANGELOG.md
- src/lib/Filters.js
- src/lib/queryFromFilters.js
There are options "startsWith" and "endsWith" in the filter input for string fields, but "contains string" option is for some reason missing, so I made this change. In my opinion it is pretty important feature for people who use dashboard to browse their parse data.
It does filtering case insensitively for now. Could maybe add later a checkbox for selecting case sensitivity.
> Added/fixed a filtering option "contains string" for String fields.

- CHANGELOG.md
- src/components/BrowserFilter/FilterRow.react.js
- src/lib/Filters.js
- src/lib/queryFromFilters.js
As requested in issue #720 
What do you think, is this something you were looking for?
> Add ability to search Object columns

- CHANGELOG.md
- src/components/BrowserCell/BrowserCell.react.js
The tables look broken on Safari when there are empty cells:
And after this patch:
> Fix display bug on safari when table has empty cells ('')

- CHANGELOG.md
- src/components/StringEditor/StringEditor.react.js
- src/dashboard/Data/Browser/Editor.react.js
Makes editing objects a lot more fun.
> Feature: When editing Object or Array fields the data is displayed in a prettier format and the textarea is resizable

- CHANGELOG.md
- src/lib/stores/PushAudiencesStore.js
See https://github.com/parse-community/parse-server/pull/3861
> Enabling audiences UI

- src/dashboard/Data/Jobs/Jobs.react.js
- src/dashboard/Data/Jobs/JobsData.react.js
- src/lib/ParseApp.js
- src/lib/stores/JobsStore.js
This goes side by side with https://github.com/parse-community/parse-server/pull/3927
This restores the `Scheduled Jobs` section, keeps the `All Jobs` to run them manually, modernizes the network calls by using Parse._request instead of AJAX.
> Restore jobs scheduling interface and capabilities

- CHANGELOG.md
- src/dashboard/Data/Jobs/Jobs.react.js
Added on the empty Scheduled Jobs page a message that notifies about jobs not being run by parse-server but requires further setup.
> Scheduled jobs message

- CHANGELOG.md
- src/dashboard/Data/Jobs/JobScheduleReminder.react.js
- src/dashboard/Data/Jobs/Jobs.react.js
- src/dashboard/Data/Jobs/JobsForm.react.js
- src/dashboard/TableView.react.js
* When there are no scheduled jobs
* When scheduling a new job
* When viewing the list of current scheduled jobs
> Show jobs schedule reminder message

- CHANGELOG.md
- src/components/BrowserFilter/FilterRow.react.js
Contributing to #557
Fixes two bugs with number input in filters:
- when input has a negative number (to reproduce in master: typing a "-" char will lead to "NaN" being displayed)
- when input is empty (to reproduce in master: typing a valid number and deleting with backspace will lead to "NaN" being displayed)
> fix filter for negative and empty number input

- src/components/BrowserCell/BrowserCell.react.js
- src/dashboard/Data/Browser/Editor.react.js
- src/lib/Constants.js
Dashboard currently breaks when viewing classes that contain a `Polygon` type. This pull request adds support for the new type.
> Add support for Polygon type

- CHANGELOG.md
- src/dashboard/Push/PushDetails.react.js
- src/dashboard/Push/PushIndex.react.js
This fix addresses the issue outlined in #539 by being able to now render the title and body keys from the alert object.
> Updated iOS alert object to display title and body detail

- src/dashboard/Push/PushNew.react.js
Conditionally add an audience_id property if a saved audience is used for a push on the dashboard.
> Send audience ID with push body.

- package.json
- src/dashboard/Push/PushNew.react.js
- src/lib/extractTime.js
- src/lib/tests/extractTime.test.js
- Enable the push/expiration time fields if the server supports scheduled push
[Related PR #4137](https://github.com/parse-community/parse-server/pull/4137)
> Support push time, expiration time, and expiration interval

- CHANGELOG.md
- src/dashboard/Data/Browser/BrowserTable.react.js
This PR fixes issue #590  (but does not fix issue #756 )
It might not be the best solution (the problem might be deeper in the system), but it is a 
one-line workaround that just does what is needed and prevents dashboard users from creating fatal damage to their Date arrays just by opening the field and losing focus thus saving changes.
BTW: I had troubles running the jest tests on windows, spend a few hours figuring out how to do it but I was not able to. It really drives me crazy. Could someone please try it on windows and update CONTRIBUTING.md with info how to do it? First I was getting `'NODE_PATH' is not recognized as an internal or external command`, then I found out I need to do some changes in package.json:
```
"build": "SET NODE_ENV=production && webpack --config …
```
> Updating array of Dates no longer converts it to array of strings

- .travis.yml
- CHANGELOG.md
- README.md
- src/dashboard/Data/Jobs/Jobs.react.js
- src/dashboard/Push/PushNew.react.js
- src/lib/ParseApp.js
- This is somewhat different from parse.com and probably more efficient
See also: https://github.com/parse-community/parse-server/pull/4130
> Adds interface for localized push notifications

- src/dashboard/Data/Browser/Browser.react.js
When sorting columns, an additional ordering was always added on createdAt which cause issues on large collection.
This PR removes this additional descending, therefore, index management should be easier.
> Removes forcing sort on createdAt

- README.md
Just a little improvement in the sample code readability
> Enable JavaScript syntax highlighting in README

- README.md
Since [1.1.1](https://github.com/parse-community/parse-dashboard/compare/1.1.0...1.1.1#diff-6e7f8f893e54e5b6f584a6f7f5d4bf69R49) options to the middleware are passed as an object. This is not reflected in the main README file where for instance `allowInsecureHTTP` is still passed as an standalone `boolean`:
```javascript
var allowInsecureHTTP = false
var dashboard = new ParseDashboard({
// Parse Dashboard settings
}, allowInsecureHTTP);
```
Where the sample code should be in the form:
```javascript
var options = { allowInsecureHTTP: false };
var dashboard = new ParseDashboard({
// Parse Dashboard settings
}, options);
```
The lack of this update was driving me crazy for a couple of hours. Hope this help others.
> Update middleware sample code in README

- src/lib/ParseApp.js
The newly added `supportedPushLocales` causes the **Push** section of the dashboard to break if it is not present. This adds a one-line check to set an empty array if push locales are not set. This does not remove the option to set a push locale however, it just provides no options as can be seen below.
> Fixes missing supportedPushLocales in #811

- src/dashboard/Push/PushNew.react.js
Currently, selecting an audience results in push notifications being sent to all installations because the query is `{}`. This commit makes sure that the Push query (`{}`) is replaced with the query found in the Audience object.
> Include PushAudience query

- src/lib/Constants.js
I love parse-server & parse-dashboard.
I have found that the _PushStatus class is specially handled, but that's the definition is missing.
It's a simple changes, but I'm glad to be able to send PR to parse-dashboard.
Thank you!
> _PushStatus add to SpecialClasses

- CHANGELOG.md
- src/components/BrowserFilter/FilterRow.react.js
Fixes a bug introduced in 1.1.1 causing any 1-digit number filter to yield no results.
https://github.com/parse-community/parse-dashboard/issues/831
> Fix filtering with a 1-digit number (#831)

- CHANGELOG.md
- Parse-Dashboard/parse-dashboard-config.json
- README.md
- package.json
- src/components/Sidebar/Sidebar.react.js
- src/components/Sidebar/SidebarSection.react.js
- src/dashboard/Apps/AppsIndex.react.js
- src/dashboard/DashboardView.react.js
- src/lib/ParseApp.js
Easily distinguish your app cards.
```
{
"apps": [{
"serverURL": "",
"appId": "",
"masterKey": "",
"appName": "",
"iconName": "",
"backgroundColor":"#000000"
}],
"iconsFolder": "icons"
}
```
> add background color in AppCard

- package.json
- src/components/PushAudienceDialog/PushAudienceDialog.react.js
- src/components/PushAudiencesSelector/PushAudiencesOption.react.js
- src/components/PushAudiencesSelector/PushAudiencesSelector.react.js
- src/dashboard/Push/PushAudiencesData.react.js
- src/lib/ParseApp.js
- src/lib/stores/PushAudiencesStore.js
- Fix issue affecting bad requests with audience_limit
- Adds support for sizing audiences in the dashboard running counts on _Installation table
> Push Audiences improvements

- src/dashboard/Push/PushConstants.js
This goes together with the update done here https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1375 to add support for tvOS to the iOS/OSX SDK. 
It basically just adds the `tvos` audience to the push UI.
> Add tvOS support to push targeting

- package.json
- src/dashboard/Dashboard.js
- src/dashboard/Data/Browser/Browser.react.js
Title of browser with class name currently opened #868
> Add classname to browser title

- src/dashboard/Apps/AppsIndex.react.js
Hi, in a project using Parse Server, I'm trying to connect the Parse Dashboard as a middleware and don't need multiple apps.
Since I don't need multiple apps, I don't want to be redirected to the apps screen, which is only an extra step to the content.
This PR is simply to open the conversation, I browsed the code and found that it would be difficult to build my use case properly and decided to find the easiest way to achieve my goal. For now it's simply redirecting to the browser every time you reach the `AppsIndex` page and the `AppsManager` only knows one app.
More ideas would be to:
- prevent the Apps selectors toggle
- remove the caret when in "single app mode"
Any feedback welcome, I'd especially like pointers on how to plug this feature properly.
> Redirect to the first app browser when only a single app is registered

- src/components/DataBrowserHeaderBar/DataBrowserHeaderBar.react.js
- src/dashboard/Data/Browser/Browser.react.js
- src/dashboard/Data/Browser/BrowserTable.react.js
- src/dashboard/Data/Browser/BrowserToolbar.react.js
- src/dashboard/Data/Browser/DataBrowser.react.js
- src/lib/ParseApp.js
In a project using Parse Dashboard as a middleware of a Parse Server, I want to disable the actions modifying the schema.
I know there is way to fail these actions when using the `readOnlyMasterKey`, but I need to let my user add / edit / delete rows, I just want them to not change the schema. The best way I found so far is to hide the buttons:
- "Create a class" in the Browser
- "Add a column" in the BrowserTable
- "Security" and all options related to columns and classes from the Edit dropdown
To support that, I added a new `preventSchemaEdits` option to apps, defaulted to `false`.
Eg:
```
{
"apps": [{
"serverURL": "http://localhost:1337/parse",
"appId": "hello",
"masterKey": "world",
"appName": "",
"iconName": "",
"primaryBackgroundColor": "",
"secondaryBackgroundColor": "", …
```
> Add preventSchemaEdits option to apps and hide or disable buttons to manipulate classes and columns

- Dockerfile
- Parse-Dashboard/app.js
- Parse-Dashboard/index.js
- README.md
when running with docker, as the local IP address is different from the dashboard
all the security features would light up.
This --dev flag let anyone run the dashboard locally easily
> Adds dev flag

- src/dashboard/Data/Browser/RemoveColumnDialog.react.js
#968 Remove default value in 'Remove column modal' add a placeholder and disable button if no column is selected.
> feat(RemoveColumnDialog): Remove default value and add placeholder

- CHANGELOG.md
- src/dashboard/Push/PushNew.react.js
Hello,
Because of the use of a generic method  _formatErrorMessage_ (src/dashboard/Push/PushNew.react.js) an inappropriate message is shown when no target audience is selected .
Before
After
Wassime.
> Correct inappropriate error message when no target audience is selected.

- .travis.yml
- CHANGELOG.md
- package-lock.json
- package.json
Skip Cleanup to allow for `webpack` to be found and the package to be built.
https://travis-ci.org/parse-community/parse-dashboard/builds/542515609?utm_source=github_status&utm_medium=notification
> ⚡️ Release 1.3.3

- src/lib/getFileName.js
- src/lib/tests/getFileName.test.js
Fixes #1121 
This PR fixes the removal of [hex prefix generated by parse server](https://github.com/parse-community/parse-server/blob/d83a0b680854f52ce30205d3558c0133d7f8cf19/src/Controllers/FilesController.js#L29) and add tests for this function.
> Fix getFileName lib to display correctly the filename

- src/components/Sidebar/AppsMenu.react.js
This PR fixes the layout issue that occurs when an app name is too long.
The screenshot of the issue:
and after this PR:
> fix: AppsMenu broken layout when app name is too long

- src/components/PermissionsDialog/PermissionsDialog.react.js
- src/components/PermissionsDialog/PermissionsDialog.scss
Allows users to set/unset CLP to run `count` queries through the `SecurityDialog` component.
Fixes #1165
> feat: Include "count" CLP option

- package-lock.json
- package.json
- src/components/Toggle/Toggle.react.js
- src/dashboard/Data/Browser/AddColumnDialog.react.js
- src/dashboard/Data/Browser/Browser.react.js
- src/dashboard/Data/Browser/Browser.scss
- src/lib/stores/SchemaStore.js
- src/parse-interface-guide/routes.js
This PR means to add the feature developed in [#5835](https://github.com/parse-community/parse-server/pull/5835) to Parse-Dashboard, that includes the option to set required fields and default values to the schema. This feature is available for Parse-Server version >= 3.7.0 and all field types, except Relation.
Some screenshots:
- String
- Boolean
- Field creating with an invalid default value
- Handle error on object creation
> feat: Add required and default value options

- src/components/Sidebar/Sidebar.scss
- src/dashboard/Apps/AppsIndex.scss
Fix #1194. I Reverted the changes applied [here](https://github.com/parse-community/parse-dashboard/commit/51ab46d569c9da55fa30aefc3bf9c872bd17695b) and standardized the font-family for Dosis
Screenshot:
@davimacedo and @natanrolnik let me know your feedback.
> fix: Fonts on AppsIndex

- package-lock.json
- src/components/DataBrowserHeaderBar/DataBrowserHeaderBar.react.js
The `DragDropContext` was removed in version 9.0.0 in react-dnd, as we can see [here](https://github.com/react-dnd/react-dnd/releases/tag/v9.0.0).
> fix: Breaking changes in react-dnd version 9.x

- src/components/DataBrowserHeaderBar/DataBrowserHeaderBar.react.js
- src/components/DataBrowserHeaderBar/DataBrowserHeaderBar.scss
- src/dashboard/Data/Browser/Browser.react.js
- src/dashboard/Data/Browser/BrowserTable.react.js
Allows users to select all visible objects. If lazy loading fetches more data, the select all checkbox is unset.
>  feat(Database Browser): Select all objects

- src/components/BrowserCell/BrowserCell.react.js
- src/dashboard/Data/Browser/BrowserTable.react.js
Fixes #983
When rendering/editing `Array` or `Object` type fields on `Database Browser`, we must avoid any transformations of generic data to the `ParseObject` format. Since these fields are generic, we can't assume it will contain Parse related content.
> fix(Database Browser): Avoid Parse transformations on array and object fields

- src/dashboard/Data/Config/Config.react.js
- src/dashboard/Data/Config/ConfigDialog.react.js
- src/lib/stores/ConfigStore.js
Adds a property to Parse Config parameter to make it only retrievable with master key.
> Add masterkey parameters

- package.json
- webpack/base.config.js
[Source](https://github.com/webpack-contrib/sass-loader/blob/master/CHANGELOG.md#800-2019-08-29)
> fix: Update base config to work with sass-loader 8.x

- package.json
- src/components/BrowserCell/BrowserCell.react.js
- src/components/BrowserRow/BrowserRow.react.js
- src/dashboard/Data/Browser/Browser.react.js
- src/dashboard/Data/Browser/BrowserTable.react.js
- src/dashboard/Data/Browser/DataBrowser.react.js
Currently, in order to copy cell content, users need to edit the cell, select all content manually and copy. This PR allows users to copy the entire cell content just by selecting the cell and pressing CTRL+C (or CMD+C).
When a value is copied to the clipboard, a message will appear on the bottom right of the screen.
Also, it is not possible to copy sensitive data such as `_User` password and sessionToken.
> feat(Database Browser): Copy cell value using CTRL+C

- src/dashboard/Data/Browser/DataBrowser.react.js
@douglasmuraoka Unfortunately `shouldComponentUpdate` is not working accordingly in `DataBrowser.react.js` and it is causing many bugs in the last release:
- Columns are not resizing
- Menu is not updating when there is a row selection
- Select all stopped working
So I think it would be better remove it for now, and then work to optimize it later.
Close https://github.com/parse-community/parse-dashboard/issues/1270
> Fix: Data Browser is not updating accordingly

- src/components/BrowserRow/BrowserRow.react.js
- src/dashboard/Data/Browser/BrowserTable.react.js
- src/dashboard/Data/Browser/Editor.react.js
close https://github.com/parse-community/parse-server/issues/6049
> Force pointer array items to always be pointers

- src/dashboard/Data/Browser/Browser.react.js
Only do a complex query for `createdAt` instead of `-createdAt`
This should resolve this issue: https://github.com/parse-community/parse-dashboard/issues/1309
> Prevent the duplicate last entry when sorting by _createdAt

- CHANGELOG.md
- package-lock.json
- package.json
@dplewis I can also wait for you to fully review #1334 so we can add to this release?
> prepare for 2.0.4

- src/dashboard/Data/Browser/Browser.react.js
After #1334, the infinite scroll is no longer loading the next set of objects. This commit undoes #1334, and tries another approach in order to fix the original problem.
> fix(Browser): Infinite scroll not working

- src/dashboard/Data/Browser/Browser.react.js
When clicking a relation column, data from the current class rows can cause a type mismatch in the targetClass.
Class "One" schema:
```
myfield: { type: 'Object' }
two: { type: 'Relation', targetClass: 'Two' }
```
Class "Two" schema:
```
myfield: { type: 'String' }
```
1. Create at least 1 object of class "One" with an object saved in myfield column.
2. Viewing "One" in parse dashboard browser, click the "two" relation button.
Because the Browser state has the data from class "One", on initial load of the BrowserTable for the "Two" relation, the BrowserCell for the myfield column will attempt to render the object content from the "One" row.
> Clear state.data when setting relation to prevent column type mismatch.

- src/components/PermissionsDialog/PermissionsDialog.react.js
As discussed here https://community.parseplatform.org/t/permission-denied-for-action-find-on-class/365/9, it seems that the latest version of the dashboard is not setting pointer CLPs correctly. The details can be found in the thread.
This change fixes it. For instance, if I set the following CLPs
I get the following CLP object
```
"classLevelPermissions": {
"find": {
"pointerFields": [
"user",
"users"
]
},
"count": {
"pointerFields": [
"user",
"users"
]
},
"get": {
"pointerFields": [
"user",
"users"
]
},
"create": {},
"update": {},
"delete": {},
"addField": {},
"protectedFields": {
"*": []
}
}
```
I believe that the most important change in behavior that this PR fixes is that now if I `find` as an user (with session token) with exactly the same CLP settings shown in the screenshot above …
> Fix pointer CLPs

- src/components/Toolbar/Toolbar.scss
> Fixes toolbar overlap to page title

- .github/stale.yml
- src/lib/tests/e2e/dashboard.e2e.test.js
Similar to https://github.com/parse-community/parse-server/pull/6810
Fixes labels, allow stalebot for only issues.
> chore: Remove wontfix label from Stalebot

- src/components/GeoPointEditor/GeoPointEditor.react.js
- src/components/TextInput/TextInput.react.js
- src/dashboard/Data/Browser/EditRowDialog.react.js
- update fields automatically when they are updated on server
- don't update array, object and polygon when no changes are in the field
- GeoPointEditor component added componentWillReceiveProps for values change
- TextInput component textarea mode added rows props to be used
> Fixes EditRowDialog

- src/dashboard/Data/Browser/Browser.react.js
- src/dashboard/Data/Browser/DataBrowser.react.js
- src/lib/ColumnPreferences.js
- src/lib/ParseApp.js
Closes #172.
With this PR, you can specify "columnPreference" in your app settings.
This can easily allow you to order and size specific columns consistently across multiple devices and classes.
```
"apps": [
{
"serverURL": "http://localhost:1338/parse",
"appId": "hello",
"masterKey": "world",
"columnPreference" : {
"_Role" : [
{"name":"updatedAt","width":250,"visible":true}
],
"_User" : [
{"name":"objectId","width":150,"visible":true},
{"name":"updatedAt","width":150,"visible":true},
{"name":"createdAt","width":150,"visible":true},
{"name":"firstName","width":150,"visible":true},
{"name":"lastName","width":150,"visible":true}
]
}
}
],
```
The remaining fields will still display in the "Manage Columns" option, but will be invisible.
If a class isn't specified in `columnPreference`, the …
> (feat) Column Preference for Data Browser

- package-lock.json
- package.json
- src/components/BrowserCell/BrowserCell.react.js
- src/components/Tooltip/PopperTooltip.react.js
Added a tooltip for readOnly fields.
Showing tooltip on doubleClick event.
> Added tooltip for readonly fields

- src/dashboard/Data/Browser/Browser.react.js
https://github.com/parse-community/parse-dashboard/issues/1693
> exculde hidden culomns

- src/components/BrowserCell/BrowserCell.react.js
Showing 'auto' for auto-generated fields while creating new row or editing cloned rows.
Bascially for readOnly fields while adding new row.
> showing '(auto)' for auto-generated fields

- src/dashboard/Data/Browser/Browser.react.js
- src/dashboard/Data/Browser/DataBrowser.react.js
when adding new row, added ESC key binding to cancel add new row
> Added ESC key binding

- src/dashboard/Data/Browser/Browser.react.js
issue - https://github.com/parse-community/parse-dashboard/issues/1551
- updated initial query to sort records according to 'objectId'
- updated fetch next page query to get new records according to 'objectId'
> Infinite Scroll query update

- src/dashboard/Data/Browser/Browser.react.js
- src/dashboard/Data/Browser/BrowserTable.react.js
Added a cancel button for aborting add new row operation
> added cancel button for new row

- README.md
- src/components/DataBrowserHeaderBar/DataBrowserHeaderBar.react.js
- src/components/DataBrowserHeaderBar/DataBrowserHeaderBar.scss
- src/dashboard/Data/Browser/BrowserTable.react.js
Hello guys,
I've added a simple piece of code to prevent sorting on some columns described in columnPreferences.
For example : 
```json
{
"apps": [
{
"appId": "local_app_id",
"appName": "Local",
"appNameForURL": "local",
"javascriptKey": "local_javascript_key",
"restKey": "local_rest_api_key",
"masterKey": "local_master_key",
"production": false,
"serverURL": "http://localhost:1337/api",
"supportedPushLocales": [
"en",
"fr"
],
"columnPreference": {
"WorkerCV": [
{
"name": "createdAt",
"preventSort": true
},
{
"name": "updatedAt",
"preventSort": false
},
{
"name": "checksum"
}
]
}
}
]
}
```
It's my first open source PR so please feel free to comment if needed.
> feat(preventSort): allow preventSort from columnPreferences props

- src/dashboard/Data/Browser/DataBrowser.react.js
Hello,
This PR allow using CTRL C/V and other key biding while adding a new row using the new Adding row feature.
Before, only escape key was binded
> fix: Allow other key binding while adding new row

- src/dashboard/Data/Browser/AddColumnDialog.react.js
- src/dashboard/Data/Browser/Browser.react.js
Creating new column name starting with number gives internal server error. Now, validating column name to not accept names starting with numbers.
> Fix: Column name starting with numbers

- src/components/BrowserCell/BrowserCell.scss
- src/components/Pill/Pill.scss
- src/dashboard/Data/Browser/Browser.scss
The border around the cell is no longer covering the whole cell when selecting a cell.
The height of the row is different from the height of the cell which causes the small border. Increasing the height of cell and fixing the height of row to match the cell fixes the border issue.
> cell select height fix

- .github/workflows/ci.yml
- CHANGELOG.md
Ensures a PR modifies the CHANGELOG.md file:
Transitional solution until we move to automated releases which will generate the changelog entry.
TODO:
> ci(changelog): add changelog reminder

- CHANGELOG.md
- src/components/BrowserCell/BrowserCell.react.js
- src/dashboard/Data/Browser/EditRowDialog.react.js
- Not able to edit array of pointer field, as single click on the cell redirects to pointer class.
- Ctrl+c copies `[object Object]` instead of field json value.
- Edit modal displays wrong data for array of pointers.
Related issue: #1770
- Using Pill design for pointer fields. that will only redirect to pointer class on arrow icon click, otherwise on single should select the cell & on double click opens Editor for that cell.
- set copyableValue to json of field value.
- Using `Prase._encoding` to avoid converting object into parseObjects.
> Edit Array of pointers

- CHANGELOG.md
- src/components/Popover/Popover.scss
Modal content not visible due to sidebar.
https://user-images.githubusercontent.com/44117648/131956015-fdecaabc-3fe3-4a5d-bf8c-a4e8289c7db6.mp4
Related issue: #`1777`
Change Modal `z-index` property to +1 of z-index of Sidebar.
> Fix: Modal Z-index

- .github/workflows/docker-publish.yml
- CHANGELOG.md
Related issue: #1782 
Use GitHub Actions to push to Docker hub during merges of PRs and releases. Merges to the master branch push the latest image to `latest` on Docker Hub and releases push the latest release with the same tag name. You can see the tags this creates using my research repo: https://hub.docker.com/repository/docker/netreconlab/parse-dashboard. Version 2.2.1 of the dashboard is me testing the tagging.
This is setup to build images for multiple architectures, but currently only the `amd64` (Intel Linux) build passes.
A side-effect is it creates another tag on docker-hub called `master`, which I guess could be useful if something else is pushed after `latest`
> ci: Fix docker image pushing to Docker Hub

- .github/workflows/docker-publish.yml
Minor refactor docker ci according to parse server ci
Related issue: #0
> ci: refactor docker ci

- CHANGELOG.md
- Dockerfile
- package.json
Related issue: https://github.com/parse-community/parse-dashboard/issues/1787
> feat(docker): increase node version in docker to 12

- .github/workflows/ci.yml
- .github/workflows/docker-publish.yml
- CHANGELOG.md
- ci/CiVersionCheck.js
- ci/ciCheck.js
- ci/nodeEngineCheck.js
- package-lock.json
- package.json
- src/lib/stores/SchemaStore.js
Multiple connected issues here:
- ci is outdated, lacking multi-node environment
- missing docker build check
- outdated dependencies which require code refactoring due to major version bumps
- node compatibility issues that only come up now that the CI is testing for multiple node versions
Related issue: https://github.com/parse-community/parse-dashboard/issues/1787
- add multi-node envs
- bump dependencies
This PR does not address missing node 16 compatibility tests in CI; a few dependencies need to be upgraded for that and code refactoring is necessary; so that's separate issue.
> ci: modernize steps

- CHANGELOG.md
- src/dashboard/Data/Browser/Browser.react.js
Revert PR [#1706](https://github.com/parse-community/parse-dashboard/pull/1706) on new default sorting columns on initial load and pagination (It could lead to performance issues without new database indices.
Related issue: #1799
Revert the code modification as it is before the PR.
> fix: revert #1706 which introduced new database index requirements for pagination

- CHANGELOG.md
- src/dashboard/Data/Browser/Browser.react.js
Performance issues on initial load AND navigation when there is 50+ models registered to the ParseServer
Related issue: #1801
*First of all, i'm a totally novice to react so feel free to comment 👯*
Instead of setting the state for each model after each model count returns, I set all the class counts at the end of the compute loop. See linked issue videos for performance issue.
> perf: asynchronously fetch classes counts in sidebar to not block dashboard

- README.md
Incorrect  badges
Related issue: #n/a
- replace greenkeeper with snyk badge
- add node badge
- reorder bagges
n/a
> docs: fix README badges

- src/login/Login.js
Incorrect auto-focus in login form.
Related issue: https://github.com/parse-community/parse-dashboard/issues/1824
Add auto-focus according to error message. Parsing the error message is probably not the most robust approach, but it's good for now.
> fix: incorrect autofocus for login form input fields
